name: CI
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install the project
        run: uv sync --dev

      - name: Install libasound
        run: sudo apt-get install libportaudio2

      - name: Run tests
        run: uv run poe test